# Generated by Django 2.1 on 2024-01-15 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 14, 59, 59, 866116, tzinfo=utc)),
        ),
    ]
